baseURL = 'https://iamb4uc.xyz'
languageCode = 'en-us'
title = "Home"
defaultContentLanguage = 'en'
canonifyURLs = true


[module]
[module.hugoVersion]
extended = true
min = "0.41.0"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
lineAnchors = ''
lineNoStart = 1
lineNos = true
lineNumbersInTable = false
style = 'gruvbox'
tabWidth = 4

[params]
[params.theme_config]
appearance = "auto"
# back_home_text = "🏠"
date_format = "Jan 02, 2006"
generate_rss = true

[sitemap]
changefreq = 'daily'
priority = 0.5

[minify]
disableXML = true

[asset]
[asset.minify]
css = true
js = true


[privacy]
[privacy.disqus]
disable = true
[privacy.googleAnalytics]
disable = true
respectDoNotTrack = true
[privacy.instagram]
disable = true
simple = true
[privacy.vimeo]
disable = true
enableDNT = true
simple = true
[privacy.x]
disable = true
enableDNT = true
simple = true
[privacy.youTube]
disable = true
privacyEnhanced = true

[security]
enableInlineShortcodes = false
[security.exec]
allow = [
        '^(dart-)?sass(-embedded)?$',
        '^go$',
        '^git$',
        '^npx$',
        '^postcss$',
        '^tailwindcss$',
]
osEnv = [
        '(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\w+|(XDG_CONFIG_)?HOME|USERPROFILE|SSH_AUTH_SOCK|DISPLAY|LANG|SYSTEMDRIVE)$',
]
[security.funcs]
getenv = ['^HUGO_', '^CI$']
[security.http]
methods = ['(?i)GET|POST']
urls = ['.*']
